name: Frontend setup
description: Checkout, install Node, restore npm cache, and install frontend dependencies

runs:
  using: composite
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version-file: starter/frontend/.nvmrc

    - name: Restore npm cache
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('starter/frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install dependencies
      shell: bash
      working-directory: starter/frontend
      run: npm ci
